kind: Service
apiVersion: v1
metadata:
  name: wisecow-service
spec:
  selector:
    app: accu
  type: NodePort      
  ports:
    - protocol: TCP
      port: 4499       
      targetPort: 4499 
      nodePort: 30499 
